#!/bin/sh
NC='\033[0m'
LP='\033[1;35m'
echo -e "#################################################################"
echo -e "########################### ${LP}JOINTVECH${NC} ###########################"
echo -e "#################################################################"

./gradlew --stacktrace integrate -Psource=Aeschynomene-evenia-description

./gradlew --stacktrace integrate -Psource=CIAT22838.gnm1.XF73
./gradlew --stacktrace integrate -Psource=CIAT22838.gnm1.ann1.ZM3R

./gradlew --stacktrace integrate -Psource=legume.genefam.fam1.M65K
./gradlew --stacktrace integrate -Psource=legume.genefam.fam1.M65K.trees_ML_rooted

./gradlew --stacktrace integrate -Psource=interpro
./gradlew --stacktrace integrate -Psource=interpro-go
./gradlew --stacktrace integrate -Psource=go
./gradlew --stacktrace integrate -Psource=so
./gradlew --stacktrace integrate -Psource=plant-ontology
./gradlew --stacktrace integrate -Psource=plant-trait-ontology
