#!/bin/sh

echo ""
echo "##########################################################################################################################################"
echo "##########################################################################################################################################"
echo "##################################################### JOINTVETCHMINE INTEGRATE ###########################################################"
echo "##########################################################################################################################################"
echo "##########################################################################################################################################"
echo ""

## ontologies
./gradlew --stacktrace integrate -Psource=so
./gradlew --stacktrace integrate -Psource=go
./gradlew --stacktrace integrate -Psource=plant-ontology
./gradlew --stacktrace integrate -Psource=plant-trait-ontology

## InterPro
./gradlew --stacktrace integrate -Psource=interpro
./gradlew --stacktrace integrate -Psource=interpro-go

## LIS gene families and phylotree
./gradlew --stacktrace integrate -Psource=legume.genefam.fam1.M65K
./gradlew --stacktrace integrate -Psource=legume.genefam.fam1.M65K.trees_ML_rooted

## aesev about
./gradlew --stacktrace integrate -Psource=aesev-about

## aesev.CIAT22838.gnm1
./gradlew --stacktrace integrate -Psource=CIAT22838.gnm1.XF73.genome_main
./gradlew --stacktrace integrate -Psource=CIAT22838.gnm1.ann1.ZM3R.cds
./gradlew --stacktrace integrate -Psource=CIAT22838.gnm1.ann1.ZM3R.gene_models_main
./gradlew --stacktrace integrate -Psource=CIAT22838.gnm1.ann1.ZM3R.protein
./gradlew --stacktrace integrate -Psource=CIAT22838.gnm1.ann1.ZM3R.transcript
./gradlew --stacktrace integrate -Psource=CIAT22838.gnm1.ann1.ZM3R.iprscan
./gradlew --stacktrace integrate -Psource=CIAT22838.gnm1.ann1.ZM3R.legfed_v1_0.M65K.gfa
./gradlew --stacktrace integrate -Psource=CIAT22838.gnm1.ann1.ZM3R.legfed_v1_0.M65K.pathway


# ## TEMP FOR PATHWAYS
# ./gradlew --stacktrace integrate -Psource=G19833.gnm1.ann1.pScz.legfed_v1_0.M65K.gfa
# ./gradlew --stacktrace integrate -Psource=G19833.gnm1.ann1.pScz.pathway
